### ISSUE TITLE
Bluetooth enables itself

### ISSUE THREAD

**Issue by Amby713** [crdroidandroid/android#103]
When I pull the quick settings and disable Bluetooth, it automatically enables itself after a certain duration. I'm not sure exactly how long, but I disabled my bt so that I could just navigation and hear it on my phone, it turned on and I didn't realize it. It connected to my car and went silent and I missed my exit
Had to disable bt again and keep checking to see that it's disabled while driving.

Happened on crdroid 7.x and 8.x

**Comment by gwolf2u** [comment]
Use issue tracker repo
