### ISSUE TITLE
did not parse correctly: in valid character ',' looking for beginning of value

### ISSUE THREAD

**Issue by Hermannjosef** [crdroidandroid/android#104]
im having a issue compiling crDroid (android 11, mainly because i hate android 12/13)
OS: Arch Linux
RAM: 10 GB
cpu threads: 6
im using qemu_x86-64 to emulate the system used to compile crDroid

Full Error:

FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out
/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs
.ninja -o out/soong/build.ninja Android.bp
config file: /home/me/crDroid/out/soong/soong.variables did not parse correctly: in
valid character ',' looking for beginning of value
16:18:50 soong bootstrap failed with: exit status 1

**Comment by gwolf2u** [comment]
use issue tracker
