### ISSUE TITLE
POCO F3 Android 13: Inability to enable 120Hz in settings

### ISSUE THREAD

**Issue by DavidRLTG** [crdroidandroid/android#106]
Seriously! I looked in display settings, developer settings, everywhere, but I was unable to find any option to enable it! Except, well, Per-App refresh rate. Pretty unfortunate!

**Comment by raystef66** [comment]
Seriously? 
It's pretty nice and also obvious to have this option in QS, fast and smooth. 
So before opening an 'issue', do some research ;)
And yes, per app refresh rate is also a feature I've added...

**Comment by DavidRLTG** [comment]
Mhm. Totally a good idea to put it **aaaaaaaaaall** the way at the bottom of bonus QS tiles.
And "do some research" how was I supposed to know???
and yes I know, but someone didn't force you to do this so..
*shrug*

**Comment by raystef66** [comment]
Maybe if things are new to you it's doesn't mean you'd have to look for it thorughouly right.
And instead of opening a kinda rude 'issue' maybe join the +-3k F3 group...you'd have had an answer in a minute ;)

**Comment by DavidRLTG** [comment]
Dude, I was asking a valid question. I wasn't rude
and okay, but how, how was I supposed to know it's in QS and not settings?
and I have no idea about that group..
Now please, let's not argue on Github. Christ! I got your point, I disagree with you and I do not understand you but I won't talk about it here..
Have a good day, sir.

**Comment by raystef66** [comment]
'egoistic fellow'...'without the majority's consent'....'Atleast state on the XDA page'...'Have a bad day'....LMAO

**Comment by gwolf2u** [comment]
> > Seriously? It's pretty nice and also obvious to have this option in QS, fast and smooth. So before opening an 'issue', do some research ;) And yes, per app refresh rate is also a feature I've added...
> > Ah yes...and these builds come for free you know. Seriously...
> 
> Excuse me you egoistic fellow, purpousefully REMOVING the 120hz option from Settings isn't very appretiated. Sure, add the 120hz QS tile, but why remove the option from Settings??? Also, I'm pretty sure that the feature to chage refresh rate per app is already in Android? Please do not remove features without the majority's consent, especially ones that are useful and could confuse people when they aren't there. Atleast state on the XDA page or in the README that you put it inside of the QS. Have a bad day.

by default the option is not there
simple as that
was not removed intentionally since there was no focus for it as there's another way to achieve same effect
