### ISSUE TITLE
(re)Vanced vs Signature spoofing

### ISSUE THREAD

**Issue by Dum4G** [crdroidandroid/android#107]
Excuse me for the wrong place to ask, I suppose this is public place where someone experienced may come and explain me where the problem is.

I'm still rocking my old Oneplus 5T with stock Android 8 + Magisk 20.4 + EdExposed 0.4.6.4 (YAHFA). A special version of YT Vanced that relies on signature spoofing works flawessly here with the Xposed module posted down below.

However, I got Poco F2 Pro and my goal is to go completely rootless-LSPosedless using only those features that custom ROM offers. When I try to grant older Vanced builds a spoofing permission it launches without letting me to log in, the only relevant log is:
`11-05 17:22:20.754 W/ProtoDataStoreFlagStore(14613): java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.google.android.youtube, sha256=[a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc], atk=false, ver=224312037.true (go/gsrlt)`

I tried the most recent reVanced build from the same person with a tweaked manifest to grant the spoofing permission and it simply crashes with the following error:

https://gist.githubusercontent.com/Dum4G/f6c0fd8b7cf1e783f89aac6eb0b8199e/raw/fc3972c9fcbaf724fcc34899b92c2a9b29da3da0/gistfile1.txt

I tried to:

Install Vanced 15.43.32 before anything else, no luck
Restart my phone
Close Vanced, regrant a permission
Clear app data, regrant a permission
Try different versions 16.02.35, 16.49.37, 17.33.42
Switch between different crDroid versions: 7.something latest, 8.9, 8.10, 9.0
Even tried ArrowOS 11 to see if there's a different implementation
Apply Vanced over OG YT - obviously failed to install

Can someone verify if this Xposed module does something special specifically for Youtube app? How is it different from current spoofing method? Maybe it does something trickier that allows Vanced to be installed over original YT? If so, it would be cool to enable signature spoofing right in the installer popup so the app could be installed despite of different signatures when permission is granted.

Here is the Xposed module (rename to APK)
[FakeYt.2.0.zip](https://github.com/crdroidandroid/android/files/9946632/FakeYt.2.0.zip)

and Vanced apks I tried to use
https://dropmefiles.com/ZMEzx

Best regards

**Comment by gwolf2u** [comment]
You are asking for support for a 3rd party app, on an old android revision we no longer support and with signature spoofing that even if we've added support for, is kind of hard to fix potential bugs 
So for now, sorry to say, but your use case is not kind of crDroid specific so you'll need to seek support for this in a dedicated community like xda
Good luck
