### ISSUE TITLE
Redmi note 8 (ginkgo) crushes on crDroid 9.0

### ISSUE THREAD

**Issue by FreePhoenix888** [crdroidandroid/android#108]
Sometimes (for me the 3-nd time in 10 days) a lot of apps begin to crash
Logs before opening an app: 
[2022-11-10-21-21-51.txt](https://github.com/crdroidandroid/android/files/9994119/2022-11-10-21-21-51.txt)
I did not find any patterns in the appearance of this bug

**Comment by gwolf2u** [comment]
Use issue_tracker

**Comment by FreePhoenix888** [comment]
@gwolf2u , where it is?

**Comment by gwolf2u** [comment]
Pinned repo
