### ISSUE TITLE
Building for Pixel 3a XL (bonito) fails with a system_ext partition error, but fixing it doesn't let me install the ROM

### ISSUE THREAD

**Issue by bigfloppa234** [crdroidandroid/android#111]
Building the ROM gives me the error "Partition system_ext is part of group google_dynamic_partitions which does not have enough space free (581472256 requested, 3524956160 used out of 4068474880)" and when I resize the partition size in the BoardConfig-common file it fixes it. However, whenever I go to install it after a successful build, I get error 7 in TWRP ("Error applying update: 7 (ErrorCode::kInstallDeviceOpenError)")

![TWRP](https://user-images.githubusercontent.com/104149053/221386490-fdd7f558-45bb-408e-aa49-fc5ff9fed819.png)

Using LineageOS's "[android_device_google_bonito](https://github.com/LineageOS/android_device_google_bonito)" repository for the device stuff and the "[android_kernel_google_msm-4.9](https://github.com/LineageOS/android_kernel_google_msm-4.9)" kernel

**Comment by neobuddy89** [comment]
Wipe System

**Comment by bigfloppa234** [comment]
Same issue after using `fastboot erase system`
