### ISSUE TITLE
Is source currently broken? xternal/rsync/Android.bp:1:1: module "rsync" variant "android_arm64_armv8-a": depends on //external/zstd:libzstd which is not visible to this module You may need to add "//external/rsync" to its visibility

### ISSUE THREAD

**Issue by DrFunkenbreakz** [crdroidandroid/android#118]
I was able to build last night but now getting the following after latest sync

[ 98% 393/398] analyzing Android.bp files and generating ninja file at out/soong/build.ninja
FAILED: out/soong/build.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     -o out/soong/build.ninj
a --globListDir build --globFile out/soong/globs-build.ninja -t -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.build Android.bp
error: external/rsync/Android.bp:1:1: module "rsync" variant "android_arm64_armv8-a": depends on //external/zstd:libzstd which is not visible to this module
You may need to add "//external/rsync" to its visibility
17:50:01 soong bootstrap failed with: exit status 1

Thanks

**Comment by neobuddy89** [comment]
Sync again.
