### ISSUE TITLE
GAPPS/GMS

### ISSUE THREAD

**Issue by grimanos** [crdroidandroid/android#121]
I would like to build crdroid with gapps included. I found this repo https://gitlab.com/crdroidandroid/android_vendor_gapps but i see that is for android 12.1 . Is it okay if i use it to build android 13 rom?

**Comment by sileshn** [comment]
No, you can't. Use mindthegapps gitlab repo. Will involve editing your device tree. Procedure is available in the readme file of mindthegapps repo.

**Comment by diamondjohndroid** [comment]
I build an unofficial ROM for the Pixel 4A 4G.

before build, I set 
     export WITH_GMS=true;
This line alone added GApps, but the image was too large for my partition, so try it first alone. I am guessing too many google APK's where I think Bliss use shells of apps to download on first boot,  in addition to the all important GApps framework.

I added a smaller footprint GApps by adding the repository to the local manifest from Bliss. I add the two lines to local_manifest
<remote name="BlissRoms-gitlab" fetch="https://gitlab.com/BlissLabs/BlissRoms" revision="typhoon"/>
<project path="vendor/gms" remote="BlissRoms-gitlab" name="platform_vendor_gms" clone-depth="1" revision="typhoon"/>

The modify the file vendor/lineage/config/partner_gms.mk 
	Second last line (before the fi, within WITH_GMS == true IF clause) I ADD
		$(call inherit-product, vendor/gms/products/gms.mk)

I have also built using an even smaller GApps repository from RisingTECHOS

**Comment by Jordibgzashtita** [comment]
Too interested in coming with this shits. If google are not compile smartphone are GIVING LAGS, when Gapps are installed it start work smooth.... Of developers of crdeoid are here. They need investigate why when no Google apps are installed, crdroid os working with lags.... And put full manuals how for people's line me can compile with Gapps. O too don't want it but just for test.
