### ISSUE TITLE
[crDroid 9.10][marble]: OS loading stucks on "Phone is starting" if default phone or SMS app has been changed

### ISSUE THREAD

**Issue by PetbkA** [crdroidandroid/android#132]
**crDroid version:** 9.10 (Android 13)
**Build:** TQ3A.230901.001
**Build Date**: 2023.10.15
**Device:** Xiaomi Redmi Note 12 Turbo (marble) 12/512 Gb

Changing default SMS or phone app leads OS to stuck on `Phone is starting` message. Tried with:
- *QkSMS* for SMS;
- *True Phone* and *Simple Dialer* for phone app.

**Workaround**: remove app folder from `/data/app` via recovery.

Tried to get boot logs with no avail - logcat that TWRP can get doesn't have records for boot period

**Comment by gwolf2u** [comment]
Wrong place for reporting bugs

**Comment by ShevT** [comment]
Fixed Oct 14, 2023.
Perhaps the maintainer has not updated the sources.
