### ISSUE TITLE
bulgarian language NOT correctly translated. there is chinese words, screenshots un description

### ISSUE THREAD

**Issue by Jordibgzashtita** [crdroidandroid/android#136]
![IMG_20231113_034422](https://github.com/crdroidandroid/android/assets/149943717/ef1fe199-13fd-4f37-b850-7249f5743a22)
![IMG_20231113_034220](https://github.com/crdroidandroid/android/assets/149943717/8d956344-9047-4139-aeea-2ccc23ad16e3)
![IMG_20231113_034002](https://github.com/crdroidandroid/android/assets/149943717/c4e13bbf-4486-40fd-9762-ca0b792386ad)

**Comment by DarkJoker360** [comment]
you can check and correct these here: https://crdroid.net/translations .
for future reference, report issues here: https://github.com/crdroidandroid/issue_tracker

**Comment by gwolf2u** [comment]
issue should be fixed with next update
but in the future do submit issues in issue_tracker
