### ISSUE TITLE
Where is oneplus one source?

### ISSUE THREAD

**Issue by regalstreak** [crdroidandroid/android#14]
Where is bacon source for 7.1? Are you guys violating the GNU GPL?

**Comment by regalstreak** [comment]
Cant find it anywhere. Looked at devices organisation and what not

**Comment by neobuddy89** [comment]
We use LineageOS device trees.

**Comment by regalstreak** [comment]
How did you guys fix the "No SD Card" error on bacon? Have the same issue on hammerhead. Maybe you could point me.

**Comment by regalstreak** [comment]
I bet this: https://github.com/crdroidandroid/android_system_core/commit/a86e0e6dad83ee0daee8f4266ecaab5273fd9f6d

**Comment by regalstreak** [comment]
Thanks anyway
Deleting.

**Comment by neobuddy89** [comment]
No, that isn't issue. We were testing sdcardfs commit - which didn't work out for most devices - so reverted.
Please use latest sources from LOS to build hammerhead. I built hammerhead 2 weeks back - it was good.

**Comment by regalstreak** [comment]
Nono I aint building crdroid. I was adding support for hammerheadcaf on halogenOS. One of the leads added this commit and it fucked my device up lol

Will merge after testing https://review.halogenos.org/#/c/3357/

**Comment by neobuddy89** [comment]
You get errors because of selinux.
Sepolicy changes are here:
https://github.com/crdroidandroid/android_system_sepolicy/commits/7.1-sdcard

**Comment by neobuddy89** [comment]
Oops, that's already there.
So those needs to be reverted too if you are reverting one in system/core.

**Comment by regalstreak** [comment]
Got it. Thought it might be something related to the contexts. Thanks a lot man
