### ISSUE TITLE
cr9: cant downgrade from 9.11 to 9.9 on Lavender with twrp

### ISSUE THREAD

**Issue by g6094199** [crdroidandroid/android#140]
also trying to swap to pure lineage doent work.

result is always: no boot and return straight to twrp.

**Comment by gwolf2u** [comment]
clean install
downgrade not always possible and for sure not suggested

**Comment by g6094199** [comment]
far away from beeing usefull answer.

next is: always do backups, right?

**Comment by gwolf2u** [comment]
> far away from beeing usefull answer.
> 
> next is: always do backups, right?

You can't downgrade if encrypted (and that is default on), reason I still follow my statement from above
But yeah, always backup
