### ISSUE TITLE
Allegations of Logo Plagiarism

### ISSUE THREAD

**Issue by kum4423** [crdroidandroid/android#143]
I found this while watching YouTube. crDroid's Logo looks exactly like a certain Japanese YouTuber's channel's Logo, is this legal?
[https://www.youtube.com/@ShunRelaxChannel](https://www.youtube.com/@ShunRelaxChannel)
![世界の床屋 Shun Relax Channel](https://github.com/crdroidandroid/android/assets/3395353/93127637-6cd7-4c61-8500-68597c586bda)

**Comment by gwolf2u** [comment]
https://crdroid.net/#faq
```
Why the "eye" and not something else?
The crDroid logo is being used since the first maintainer "Cristiano Matos" added it at the beginning of the project and represents a drawing his kid did at school one day. 
```
