### ISSUE TITLE
On Screen Saver Photo Customisation Is Not Available

### ISSUE THREAD

**Issue by Hemanth6789** [crdroidandroid/android#150]
DEVICE: REDMI NOTE 8 PRO 
CR DROID VERSION: 10.1 
In settings--->display--->screen saver--->photo frame or photo table when I select on customise to select photo from gallery it shows No Photos On this Device. But photos are present in my gallery but its unable to access the photos from storage. 
![Screenshot_20240119-202511_Settings](https://github.com/crdroidandroid/android/assets/121542250/ae56a42d-3303-4023-9f2f-48d8a1cf4c80)
![Screenshot_20240119-202503_Photo Screensavers](https://github.com/crdroidandroid/android/assets/121542250/6d8c3f94-f62c-4934-855d-3379d5f51b30)

**Comment by gwolf2u** [comment]
Use issue_tracker
