### ISSUE TITLE
Double tap on square recents button is broken 

### ISSUE THREAD

**Issue by Albert753258** [crdroidandroid/android#151]
Device: poco f4
Steps to reproduce:
1. Switch to 3-button navigation
2. Disable animation in developer settings

https://github.com/crdroidandroid/android/assets/56261876/5d46c898-b2a4-4a8e-bdb9-fec15e3eab52

If you will enable animations back, double tap on recents button still works strange. Only fast tap switches applications

https://github.com/crdroidandroid/android/assets/56261876/dbd81205-1bdc-4ef1-a768-e1defad439c0

**Comment by gwolf2u** [comment]
use proper report page
