### ISSUE TITLE
Screen Cast cannot turn off phone screen while watching cast on TV

### ISSUE THREAD

**Issue by xPhoenisX** [crdroidandroid/android#153]
Hey, I have a problem with my Screen Cast. Whenever I cast something from my phone to my TV, the phone screen stays on and drains the battery. I want to turn off the phone screen while watching the cast on TV, but I can't find any option to do that. Is there a way to fix this?

**Comment by raystef66** [comment]
Use https://github.com/crdroidandroid/issue_tracker or ask in your TG group for more assistance.
