### ISSUE TITLE
Privacy Guard not working properly with Work Profile

### ISSUE THREAD

**Issue by awalis** [crdroidandroid/android#24]
Hello, hope you guys are doing well.

Thanks a million for your efforts creating and maintaining this Custom ROM. Recently, I am running crDroid 5.6 on my phone 'mido (xiaomi redmi note 4X)'. I like it, it looks quite interesting and stable, but I would like to drive your attention to one issue. 

**Expected behavior**
While using the "Shelter" app, to take advantage of the Personal and Work profiles feature. Usually one gets also two seperate Privacy Guard entries, one Privacy Guard for apps in the Personal Profile, another Privacy Guard for the apps residing in the Work Profile. This is not the case with crDroid 5.6 though.

**Issue**
In the Security & Location > Trust > Privacy Guard menu, I can find Privacy Gard for the Personal Profile apps only! 

**Workaround** 
After some fetching, I could find the Privacy Guard settings for apps from Work Profile individually, through Security & Location > Trust > Privacy Guard > the three dots menu on the top right of the screen > Advanced > under the tab "OTHER" > find and select an app from Work Profile to access its Privacy Guard settings.

**Request**
If you could fix this problem, it would be very relevant for all the privacy concerned people.

**Comment by shvchk** [comment]
Fixed in Lineage OS in June, see commit f98664e and [Changelog 23 post](https://lineageos.org/Changelog-23/)

**Comment by awalis** [comment]
Hello @gwolf2u, 
has it been fixed?
