### ISSUE TITLE
Cannot checkout platform/prebuilts/clang/host/linux-x86: NoManifestException: [Errno 2]

### ISSUE THREAD

**Issue by samkatakouzinos** [crdroidandroid/android#25]
I receive this error when running; 
1) repo init -u git://github.com/crdroidandroid/android.git -b 10.0
2) ~/bin/repo sync from /root/crDroid;

> Checking out project platform/prebuilts/clang/host/linux-x86
> error: Cannot checkout platform/prebuilts/clang/host/linux-x86: NoManifestException: [Errno 2] No such file or directory: u'/root/crDroid/prebuilts/clang/host/linux-x86/.git/HEAD'
> error: in `sync`: [Errno 2] No such file or directory: u'/root/crDroid/prebuilts/clang/host/linux-x86/.git/HEAD'
> error: manifest missing or unreadable -- please run init

Is this a problem at my end?

**Comment by gwolf2u** [comment]
working ok now?

**Comment by samkatakouzinos** [comment]
I've decided to not pursue this for now.
