### ISSUE TITLE
Moto g7 power (ocean) failed boot

### ISSUE THREAD

**Issue by Motophan** [crdroidandroid/android#28]
Previous issue was closed incorrectly.

Build does not work on this phone. Please change "official" support to "nonworking dev pre-alpha build" so people do not waste time installing this. 

[recovery_1_.log](https://github.com/crdroidandroid/android/files/3992977/recovery_1_.log)
[dmesg_1_.log](https://github.com/crdroidandroid/android/files/3992978/dmesg_1_.log)

**Comment by gwolf2u** [comment]
this is no place to report device specific bugs
use device support page https://crdroid.net/ocean
