### ISSUE TITLE
Hi there, I am trying to build jfltexx but i am getting some errors:

### ISSUE THREAD

**Issue by gericom-hummer** [crdroidandroid/android#3]
$ brunch "your device name"
 and when i type jfltexx:
brunch "jfltexx"
including vendor/cm/vendorsetup.sh
Looking for dependencies

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=7.1.1
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=krait
TARGET_2ND_ARCH=
TARGET_2ND_ARCH_VARIANT=
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.9.0-0-MANJARO-x86_64-with-glibc2.3.4
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=NMF26Q
OUT_DIR=/home/gericom/WORKSPACE/out
============================================
bash: schedtool: command not found

#### make failed to build some targets  ####

The same is with:
brunch "cm_jfltexx-userdebug"
including vendor/cm/vendorsetup.sh
Looking for dependencies

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=7.1.1
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=krait
TARGET_2ND_ARCH=
TARGET_2ND_ARCH_VARIANT=
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.9.0-0-MANJARO-x86_64-with-glibc2.3.4
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=NMF26Q
OUT_DIR=/home/gericom/WORKSPACE/out
============================================
bash: schedtool: command not found

**Comment by neobuddy89** [comment]
sudo apt-get install schedtool

**Comment by gericom-hummer** [comment]
we are using pacman, but nevermind :) another question - what should i choose to build it for jfltexx? -3 or?

You're building on Linux

Lunch menu... pick a combo:
 1. aosp_angler-userdebug                46. cm_klteduos-userdebug 
 2. aosp_arm64-eng                       47. cm_kltedv-userdebug 
 3. aosp_arm-eng                         48. cm_kltekdi-userdebug 
 4. aosp_mips64-eng                      49. cm_kltekor-userdebug 
 5. aosp_mips-eng                        50. cm_kltespr-userdebug 
 6. aosp_x86_64-eng                      51. cm_klteusc-userdebug 
 7. aosp_x86-eng                         52. cm_klte-userdebug 
 8. cm_acclaim-userdebug                 53. cm_kltevzw-userdebug 
 9. cm_angler-userdebug                  54. cm_lux-userdebug 
 10. cm_apollo-userdebug                 55. cm_m8d-userdebug 
 11. cm_armani-userdebug                 56. cm_m8-userdebug 
 12. cm_bacon-userdebug                  57. cm_mako-userdebug 
 13. cm_bullhead-userdebug               58. cm_mint-userdebug 
 14. cm_cancro-userdebug                 59. cm_n3-userdebug 
 15. cm_clark-userdebug                  60. cm_nicki-userdebug 
 16. cm_condor-userdebug                 61. cm_oneplus2-userdebug 
 17. cm_d2att-userdebug                  62. cm_oneplus3-userdebug 
 18. cm_d2tmo-userdebug                  63. cm_osprey-userdebug 
 19. cm_d2vzw-userdebug                  64. cm_otus-userdebug 
 20. cm_d851-userdebug                   65. cm_P024-userdebug 
 21. cm_d852-userdebug                   66. cm_peregrine-userdebug 
 22. cm_d855-userdebug                   67. cm_piccolo-userdebug 
 23. cm_deb-userdebug                    68. cm_r5-userdebug 
 24. cm_ether-userdebug                  69. cm_r7plus-userdebug 
 25. cm_falcon-userdebug                 70. cm_seed-userdebug 
 26. cm_find7s-userdebug                 71. cm_shamu-userdebug 
 27. cm_find7-userdebug                  72. cm_surnia-userdebug 
 28. cm_flo-userdebug                    73. cm_t6-userdebug 
 29. cm_gemini-userdebug                 74. cm_t6vzw-userdebug 
 30. cm_h811-userdebug                   75. cm_thea-userdebug 
 31. cm_h815-userdebug                   76. cm_thor-userdebug 
 32. cm_hammerheadcaf-userdebug          77. cm_titan-userdebug 
 33. cm_hammerhead-userdebug             78. cm_tsubasa-userdebug 
 34. cm_hayabusa-userdebug               79. cm_v410-userdebug 
 35. cm_hiaeuhl-userdebug                80. cm_v500-userdebug 
 36. cm_hiaeul-userdebug                 81. cm_vegetalte-userdebug 
 37. cm_huashan-userdebug                82. cm_victara-userdebug 
 38. cm_hydrogen-userdebug               83. cm_w5-userdebug 
 39. cm_i9300-userdebug                  84. cm_wt88047-userdebug 
 40. cm_ido-userdebug                    85. cm_Z00L-userdebug 
 41. cm_jag3gds-userdebug                86. cm_Z00T-userdebug 
 42. cm_jagnm-userdebug                  87. m_e_arm-userdebug 
 43. cm_kenzo-userdebug                  88. mini_emulator_arm64-userdebug 
 44. cm_kltechnduo-userdebug             89. mini_emulator_x86_64-userdebug 
 45. cm_kltechn-userdebug                90. mini_emulator_x86-userdebug

**Comment by gericom-hummer** [comment]
ninja: Entering directory `.'
ninja: error: '/home/gericom/WORKSPACE/out/target/product/jfltexx/obj/lib/libtime_genoff.so.toc', needed by '/home/gericom/WORKSPACE/out/target/product/jfltexx/obj/SHARED_LIBRARIES/libandroid_servers_intermediates/LINKED/libandroid_servers.so', missing and no known rule to make it
make: *** [build/core/ninja.mk:152: ninja_wrapper] Error 1
make: Leaving directory '/home/gericom/WORKSPACE'

**Comment by gericom-hummer** [comment]
ninja: error: '/home/gericom/WORKSPACE/out/target/product/jfltexx/obj/lib/libtime_genoff.so.toc', needed by '/home/gericom/WORKSPACE/out/target/product/jfltexx/obj/SHARED_LIBRARIES/libandroid_servers_intermediates/LINKED/libandroid_servers.so', missing and no known rule to make it
make: *** [build/core/ninja.mk:152: ninja_wrapper] Error 1
make: Leaving directory '/home/gericom/WORKSPACE'

#### make failed to build some targets (46 seconds) ####

**Comment by neobuddy89** [comment]
Use device tree, kernel and vendor tree for your device from working cm-14.1 ROM and this error should go.

**Comment by gericom-hummer** [comment]
Can you help me a little for jfltexx? I am following the manifest's commands tutorial, but...
i am 5 years into the roms, but never build one, so it's my 1st time and it is failing :) Thanks

**Comment by neobuddy89** [comment]
If issue isn't resolved, please check with LineageOS maintainer.
This is not ROM issue but your setup issue.
