### ISSUE TITLE
OnePlus 6T: Thermal issues

### ISSUE THREAD

**Issue by tukusejssirs** [crdroidandroid/android#37]
I have no idea if I have identified the source of this issue, but I need help.

I’ve recently flashed crDroid 6.7 (latest) on OnePlus 6T with gapps and Magisk. I have observed that the phone is quite hot, i.e. 70+ °C CPU and ~40 °C battery all the time.

I have found out the `media.extractor` is using about 150-180 % of CPU all the time and even if I kill it, it autostarts again. What does it do? Is it normal for it 5o use such portion of CPU all the time?

Now, I lowered the max frequencies of all 4 cores of CPU1 (the faster one) from 2.8 to 1.84 GHz. I helped a bit—after some minutes, the phone’s cooler: 50+ °C CPU, ~37 °C battery. Even that is too high.

Just a comparison: my OnePlus 3T with Resurrection Remix 6.2.1 (based on Android 8) has idle temps of 32+ °C CPU and 26+ °C battery. That is ideal I’d like to achieve.

**Comment by gwolf2u** [comment]
Please use forum for reporting device specific bugs
GitHub is only for development mainly
