### ISSUE TITLE
repo instructions seem outdated / missing devices

### ISSUE THREAD

**Issue by aep** [crdroidandroid/android#46]
according to the README, 

    repo init -u git://github.com/crdroidandroid/android.git -b 10.0
    brunch "your device codename"

but the default.xml in 10.0 contains no device repos whatsoever, so all you get is the aosp devices. i guess there's an additional step missing to add the crdroid device repos?

**Comment by gwolf2u** [comment]
you need to create your own roomservice file with device specific source (vendor, kernel, etc)
that is indeed not on the description, just most rom builders already know that
