### ISSUE TITLE
Would a universal miracast implementation be possible? 

### ISSUE THREAD

**Issue by lividhen** [crdroidandroid/android#47]
Miracast worked in crdroid 5 out of the box. On crdroid 6 you can still view miracast devices, but if you try to cast to them the system crashes, well, quite _dramatically_. I know on some Qualcomm devices you can grab the stock wirelessdisplay hals, and it will work. Some older devics don't have these and relied on the in os feature to use miracast, which I know was depreciated in (after?) android 6. Would it be possible for someone to, I guess, cherrypick the feature back in to the rom itself? Would that just be an insane hassle or would it be a viable solution?

**Comment by gwolf2u** [comment]
Without proper HAL it won't work even if system support can be added
Depends from device to device
