### ISSUE TITLE
Assistant handles dont seem to appier when entering recents with gestures (android 10)

### ISSUE THREAD

**Issue by lividhen** [crdroidandroid/android#48]
The assistant handle/nub things don't appier when entering the recent view using gesture navigation, but they do when using physical hardware keys. Crdroid 5.12. 

Side note: them fading out bugs the crap out of me 😂. An option is stop that or just disable them entirely would be nice...
Sorry.

**Comment by gwolf2u** [comment]
GitHub issue page is for source related issues and not device specific issue
Please ask for device bugs on dedicated forum or telegram if available
