### ISSUE TITLE
Can install apps only after restart on LG G3

### ISSUE THREAD

**Issue by S7012MY** [crdroidandroid/android#5]
Same thing happens in CM 14.
Sometimes after I try to install an app from google play, I get the error 

> Failed to install app, please try again.

I'm getting the same error until I restart the phone.

**Comment by neobuddy89** [comment]
Logs, please.

**Comment by S7012MY** [comment]
Like in adb logcat?

**Comment by S7012MY** [comment]
Sorry, not able to repro anymore
