### ISSUE TITLE
error in build msm_ion not found

### ISSUE THREAD

**Issue by Gaituo** [crdroidandroid/android#51]
i triyng build crdroid 11 but have a error on source code of rom this is error:
 DANDROID_STRICT -target aarch64-linux-android30   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=fortify-source -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-int-in-bool-context -Wno-sizeof-array-div -Wno-tautological-overlap-compare -Wno-deprecated-copy -Wno-range-loop-construct -Wno-misleading-indentation -Wno-zero-as-null-pointer-constant -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-string-compare -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-pessimizing-move  -MD -MF out/target/product/sanders/obj/SHARED_LIBRARIES/gralloc.msm8953_intermediates/gr_buf_mgr.d -o out/target/product/sanders/obj/SHARED_LIBRARIES/gralloc.msm8953_intermediates/gr_buf_mgr.o hardware/qcom-caf/msm8996/display/gralloc/gr_buf_mgr.cpp"
In file included from hardware/qcom-caf/msm8996/display/gralloc/gr_buf_mgr.cpp:31:
In file included from hardware/qcom-caf/msm8996/display/gralloc/gr_buf_mgr.h:30:
In file included from hardware/qcom-caf/msm8996/display/gralloc/gr_allocator.h:36:
hardware/qcom-caf/msm8996/display/gralloc/gr_ion_alloc.h:33:10: fatal error: 'linux/msm_ion.h' file not found
#include <linux/msm_ion.h>
how to fix this?

**Comment by xNombre** [comment]
Old blobs and 3.18 kernel in use means display hal needs downgrade. Solved via PM.

**Comment by CR3SD** [comment]
Any solve for this when i want to build it for ZUK Z2?

Tree:
https://github.com/PixysOS-Devices/device_zuk_msm8996-common
https://github.com/PixysOS-Devices/kernel_zuk_msm8996
https://github.com/PixysOS-Devices/vendor_zuk
https://github.com/PixysOS-Devices/device_zuk_z2_plus
