### ISSUE TITLE
Brunch has two parameter, followed by a code name doesn't work.

### ISSUE THREAD

**Issue by eviluess** [crdroidandroid/android#56]
`bash-3.2$ brunch "dumpling"
Usage: brunch [command] [options]

Options:
  -v, --version             output the version number
  -h, --help                output usage information

Commands:
  new|n [options] [path]    Create new Brunch project in path.
  build|b [options] [path]  Build a Brunch project.
  watch|w [options] [path]  Watch Brunch directory and rebuild if something 
                            changed.
bash-3.2$ 
`

**Comment by eviluess** [comment]
I skipped brunch and eat lunch directly, it's working ....

And before this, I need to run
`source build/envsetup.sh`
rather than running
`. build/envsetup.sh`

Now it's working ....

`bash-3.2$ lunch dumpling
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
build/make/core/product_config.mk:155: error: Can not locate config makefile for product "dumpling".
17:28:46 dumpvars failed with: exit status 1
Device dumpling not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_oneplus_dumpling
Default revision: lineage-18.1
Checking branch info
Checking if device/oneplus/dumpling is fetched from android_device_oneplus_dumpling
Adding dependency: LineageOS/android_device_oneplus_dumpling -> device/oneplus/dumpling
Using default branch for android_device_oneplus_dumpling
Syncing repository to retrieve project.
Fetching projects:  50% (1/2) reporemote: Enumerating objects: 6, done.        
remote: Counting objects: 100% (6/6), done.        
remote: Compressing objects: 100% (6/6), done.        
remote: Total 321 (delta 1), reused 5 (delta 0), pack-reused 315        
Fetching projects: 100% (2/2), done.
repo sync has finished successfully.
Repository synced!
Looking for dependencies in device/oneplus/dumpling
Adding dependencies to manifest
Checking if device/oneplus/msm8998-common is fetched from android_device_oneplus_msm8998-common
Adding dependency: LineageOS/android_device_oneplus_msm8998-common -> device/oneplus/msm8998-common
Using default branch for android_device_oneplus_msm8998-common
Syncing dependencies
remote: Enumerating objects: 74, done.        
remote: Counting objects: 100% (74/74), done.        
remote: Compressing objects: 100% (54/54), done.        
remote: Total 7727 (delta 30), reused 53 (delta 13), pack-reused 7653        
Fetching projects: 100% (1/1), done.
repo sync has finished successfully.
Looking for dependencies in device/oneplus/msm8998-common
Adding dependencies to manifest
Checking if device/oppo/common is fetched from android_device_oppo_common
Adding dependency: LineageOS/android_device_oppo_common -> device/oppo/common
Using default branch for android_device_oppo_common
Checking if kernel/oneplus/msm8998 is fetched from android_kernel_oneplus_msm8998
Adding dependency: LineageOS/android_kernel_oneplus_msm8998 -> kernel/oneplus/msm8998
Using default branch for android_kernel_oneplus_msm8998
Syncing dependencies
remote: Enumerating objects: 26, done.        
remote: Counting objects: 100% (26/26), done.        
remote: Compressing objects: 100% (18/18), done.        
remote: Total 4072 (delta 6), reused 21 (delta 3), pack-reused 4046        
Fetching projects:  50% (1/2) LineageOS/android_device_oppo_commonremote: Enumerremote: Enumerating objects: 45876, done.        
remote: Counting objects: 100% (45876/45876), done.        
remote: Compressing objects: 100% (3122/3122), done.        
`

**Comment by neobuddy89** [comment]
You should try without quotes.


brunch dumpling

**Comment by eviluess** [comment]
> You should try without quotes.

I tried but failed.

**Comment by eviluess** [comment]
Now I have this issue:
```
Looking for dependencies in kernel/oneplus/msm8998
kernel/oneplus/msm8998 has no additional dependencies.
Done
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
build/make/core/product_config.mk:155: error: Can not locate config makefile for product "dumpling".
17:44:53 dumpvars failed with: exit status 1
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
build/make/core/product_config.mk:155: error: Can not locate config makefile for product "dumpling".
17:44:54 dumpvars failed with: exit status 1

** Don't have a product spec for: 'dumpling'
** Do you have the right repo manifest?

```

**Comment by neobuddy89** [comment]
That's because you are not tracking required projects.

msm8998-common
dumpling
oppo-common

**Comment by eviluess** [comment]
> That's because you are not tracking required projects.

Oh! How to do this? 
Thanks in advance.

**Comment by gwolf2u** [comment]
Add them in roomservice

**Comment by eviluess** [comment]
> Add them in roomservice

Is there a guide doc for doing this?
Thanks in advance!

**Comment by gwolf2u** [comment]
seek for repos neobuddy mentioned above in addition to adding kernel and vendor repo also (make sure to choose proper branches)
https://github.com/crdroidandroid/android_kernel_oneplus_msm8998
https://github.com/crdroidandroid/proprietary_vendor_oneplus

roomserive manifest looks like so

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>

  <remote  name="remote-name" 
           fetch="https://github.com/"
           revision="branch name" />

  <project name="github_project/github_project_name" path="/kernel/device (depends)" remote="remote-name" />

</manifest>
```

for more info, seek on Google how roomservice needs to look like for projects like LineageOS (same applies to us)

**Comment by eviluess** [comment]
> seek for repos neobuddy mentioned above in addition to adding kernel and vendor repo also (make sure to choose proper branches)
> https://github.com/crdroidandroid/android_kernel_oneplus_msm8998
> https://github.com/crdroidandroid/proprietary_vendor_oneplus
> 
> roomserive manifest looks like so
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <manifest>
> 
>   <remote  name="remote-name" 
>            fetch="https://github.com/"
>            revision="branch name" />
> 
>   <project name="github_project/github_project_name" path="/kernel/device (depends)" remote="remote-name" />
> 
> </manifest>
> ```
> 
> for more info, seek on Google how roomservice needs to look like for projects like LineageOS (same applies to us)

Great Thanks, man!

I'll check that after dinner.

**Comment by eviluess** [comment]
> seek for repos neobuddy mentioned above in addition to adding kernel and vendor repo also (make sure to choose proper branches)
> https://github.com/crdroidandroid/android_kernel_oneplus_msm8998
> https://github.com/crdroidandroid/proprietary_vendor_oneplus
> 
> roomserive manifest looks like so
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <manifest>
> 
>   <remote  name="remote-name" 
>            fetch="https://github.com/"
>            revision="branch name" />
> 
>   <project name="github_project/github_project_name" path="/kernel/device (depends)" remote="remote-name" />
> 
> </manifest>
> ```
> 
> for more info, seek on Google how roomservice needs to look like for projects like LineageOS (same applies to us)

I checked `.repo/local_manifests/roomservice.xml,` and it's already containing those info.

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project path="device/oneplus/dumpling" remote="github" name="LineageOS/android_device_oneplus_dumpling" />
  <project path="device/oneplus/msm8998-common" remote="github" name="LineageOS/android_device_oneplus_msm8998-common" />
  <project path="device/oppo/common" remote="github" name="LineageOS/android_device_oppo_common" />
  <project path="kernel/oneplus/msm8998" remote="github" name="LineageOS/android_kernel_oneplus_msm8998" />
</manifest>
```
