### ISSUE TITLE
Building for Moto Potter, needs a roomservice.xml,  what does it look like?

### ISSUE THREAD

**Issue by telent** [crdroidandroid/android#58]
Disclaimer upfront: I don't know what I'm doing and haven't built android since 2009.  So far I have guessed at the following for roomservice.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="crdroidandroid/android_device_motorola_potter" path="device/motorola/potter" remote="github" revision="10.0" />
  <project name="crdroidandroid/android_vendor_motorola_potter" path="vendor/motorola/potter" remote="github" revision="8.1" />
  <project name="crdroidandroid/android_kernel_motorola_msm8953" path="kernel/motorola/msm8953" remote="github" />
  <project name="GZR-Kernels/Optimus_Drunk_Potter" path="kernel/motorola/potter" remote="github" revision="10.0" />
  <project name="LineageOS/android_system_qcom" path="system/qcom" remote="github" revision="lineage-17.0" />
</manifest>
```

(The last two lines were based on those added for me by the brunch script, though I had to remove a leading "LineageOS/" in the `name` attribute of each, because it added  `LineageOS/LineageOS/android_system_qcom`  and `LineageOS/GZR-Kernels/Optimus_Drunk_Potter`)

However, this is  is either wrong or insufficent

```
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: test/vts-testcase/vndk/golden/Android.bp:32:1: "vts_vndk_abi_dump_zip" depends on undefined module "vndk_abi_dump_zip"
00:18:34 soong bootstrap failed with: exit status 1
ninja: build stopped: subcommand failed.
```

I note that this is a supported build, which makes me I wonder if I've taken a wrong turn prior to this somewhere because it seems like a lot of manual steps for something that you probably run in a CI system. Any pointers?

**Comment by gwolf2u** [comment]
https://github.com/crdroidandroid/android_prebuilts_abi-dumps_vndk/blob/11.0/Android.bp#L20
make sure you track our android_prebuilts_abi-dumps_vndk, even if it should
https://github.com/crdroidandroid/android/blob/11.0/snippets/crdroid.xml#L85
