### ISSUE TITLE
cepheus | 7.4 2021-03-30| selinux is not enforcing after clean install or ota update

### ISSUE THREAD

**Issue by meciks** [crdroidandroid/android#60]
crandroid version: **7.4 2021-03-30**
firmware: **V12.0.4.0.QFAEUXM**
Device: **Xiaomi MI9 (cepheus)**
gapps: NikGapps-core-arm64-11-20210130-signed.zip
magisk: not installed,i tried with it installed too 
twrp: 3.5.1_9-0
selinux is not enforcing after clean install or ota update
[https://ibb.co/TKv366S](https://ibb.co/TKv366S)
[https://ibb.co/D78hM3q](https://ibb.co/D78hM3q)

**Comment by raystef66** [comment]
Who said it should be? For now its permissive as previous ones. Next build should be enforcing.
Read all before flashing : https://forum.xda-developers.com/t/rom-11-0-official-cepheus-crdroid-v7-4-30-03-2021.4193489/post-84747299
