### ISSUE TITLE
cepheus | 2021-03-30 | missing phone call menu  gapps core

### ISSUE THREAD

**Issue by meciks** [crdroidandroid/android#61]
crandroid version: 7.4 2021-03-30
firmware: V12.0.4.0.QFAEUXM
Device: Xiaomi MI9 (cepheus)
gapps: NikGapps-core-arm64-11-20210130-signed.zip
magisk: not installed
twrp: 3.5.1_9-0
If you do not have GAPPS installed in the basic version, during the phone call there is no information that you call and missing the button to disconnect yourself

**Comment by Jabiyeff** [comment]
It's gapps issue, stop create issue again again! If your have questions ask crDroid Community group.

**Comment by raystef66** [comment]
Indeed, you have to ask on xda or in out TG group https://t.me/crdroidmi9
This can be closed as well.
