### ISSUE TITLE
hammerhead | problem with compilation

### ISSUE THREAD

**Issue by MiGoYAm** [crdroidandroid/android#62]
I have a problem with compilation crDroid 7.4 on Nexus 5 hammerhead. First error `build/make/core/shared_library.mk:60: error: done` or `hardware/qcom/display/msm8974/libgralloc/Android.mk: error: gralloc.msm8974: LOCAL_COPY_HEADERS is obsolete. See https://android.googlesource.com/platform/build/+/master/Changes.md#copy_headers` so I added to file BoardConfig.mk (thread #57). After 50% of compilation was done, another error pop out: `hardware/qcom/media/msm8974/libc2dcolorconvert/C2DColorConverter.h:33:10: fatal error: 'c2d2.h' file not found`
I looked for the missing file (in msm8974 folders) and copied it to the folder. It worked but after some time another files were missing. I repeated action each time it happend until I couldn't solve another error this way. It looked something like this: `hardware/random/directory fatal error: 'random' file not found with include <angled or something similar>` 
I have log from second error (`fatal error: 'c2d2.h' file not found`)
ps I faced the same problem while trying to compile lineage os

**Comment by xNombre** [comment]
This issue is not ROM dependent as LOS build breaks either.
I'm really sorry but we don't provide a personal help with user's device trees. Work on it yourself or look for ROM building help group or something.

**Comment by MiGoYAm** [comment]
Thanks
