### ISSUE TITLE
Bootloop since 6.17

### ISSUE THREAD

**Issue by crazydrive22** [crdroidandroid/android#66]
Hi all.

I'm building 6.x for Samsung Galaxy Tab 4 10.1 (matisse3g, matissewifi, matisselte) and 8.0 (millet3g, milletwifi, milletlte, milletltetmo). Since the Update to 6.17 all Matisse-Devices are hanging in a bootloop, while all Millet-Devices are working well. 
Here's a snip from log where the problem appears. Full log attached. Any ideas?

Cheers Martin

--------- beginning of crash
04-25 08:32:06.257   498   498 E AndroidRuntime: 
*** FATAL EXCEPTION IN SYSTEM PROCESS: main
04-25 08:32:06.257   498   498 E AndroidRuntime: java.lang.RuntimeException: Failed to boot service com.android.server.trust.TrustManagerService: onBootPhase threw an exception during phase 600
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:162)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.server.SystemServer.lambda$startOtherServices$4$SystemServer(SystemServer.java:2250)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.server.-$$Lambda$SystemServer$813bCb-sIgSt_nLX3TjXw4tpgpc.run(Unknown Source:30)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.server.am.ActivityManagerService.systemReady(ActivityManagerService.java:9066)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.server.SystemServer.startOtherServices(SystemServer.java:2131)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.server.SystemServer.run(SystemServer.java:538)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.server.SystemServer.main(SystemServer.java:365)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)
04-25 08:32:06.257   498   498 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.keystore.IKeystoreService.onKeyguardVisibilityChanged(boolean, int)' on a null object reference
04-25 08:32:06.257   498   498 E AndroidRuntime:   at android.security.KeyStore.onUserLockedStateChanged(KeyStore.java:1075)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.server.trust.TrustManagerService.setDeviceLockedForUser(TrustManagerService.java:697)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.server.trust.TrustManagerService.refreshDeviceLockedForUser(TrustManagerService.java:684)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.server.trust.TrustManagerService.onBootPhase(TrustManagerService.java:215)
04-25 08:32:06.257   498   498 E AndroidRuntime:   at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:159)
04-25 08:32:06.257   498   498 E AndroidRuntime:   ... 9 more
04-25 08:32:06.338   708   708 E AndroidRuntime: FATAL EXCEPTION: main
04-25 08:32:06.338   708   708 E AndroidRuntime: Process: com.android.systemui, PID: 708
04-25 08:32:06.338   708   708 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause

[log_crdroid_6_17_matissewifi.txt](https://github.com/crdroidandroid/android/files/6410903/log_crdroid_6_17_matissewifi.txt)

**Comment by gwolf2u** [comment]
auto closed due to inactivity

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_frameworks_base/commit/7662cbadce172fa65ab0cc12efa37235edb1468e

Not tested.
