### ISSUE TITLE
Juice | Bluetooth disconnect loop on 7.7

### ISSUE THREAD

**Issue by TheVekter** [crdroidandroid/android#69]
I upgraded to the latest build (June 28th) and my Bluetooth now disconnects a few seconds after connecting. The option slides to "off" for a moment before re-enabling itself. There's also a small dialog that flashes for half a second but I'm unable to read it. I'm on the Poco M3 build.

Logcat attached. It covers a few instances of this happening.
[2021-06-28-08-13-53.txt](https://github.com/crdroidandroid/android/files/6731838/2021-06-28-08-13-53.txt)

**Comment by gwolf2u** [comment]
please submit info to device maintainer on forum or telegram chat
