### ISSUE TITLE
Ambient Display QS tile removed after reboot.

### ISSUE THREAD

**Issue by hokiealumnus** [crdroidandroid/android#7]
This one I confirmed myself. It has affected other tiles before and Pranav believes it to be a permissions problem. 

Reproduce by:

Add Ambient Display tile to quick settings (and verify its use, that it stays while doing other things, etc.).
Reboot.
Ambient Display tile is no longer in Quick Settings and needs to be re-added manually.

**Comment by neobuddy89** [comment]
Cannot be reproduced on Nexus 6 (shamu).
However, Ambient Display tile is now replaced with Ambient-Lifttowake tile.

https://github.com/crdroidandroid/android_frameworks_base/commit/345bec3f8761aec0f38adb24f8ee6148c1210fa3
https://github.com/crdroidandroid/android_frameworks_base/commit/d9f0838e6a63f4ca1b4cb54cbc14cb8c5e79efde

**Comment by hokiealumnus** [comment]
I made a mistake on this report. "Ambient Display" tile should have read "Live Display". This bug is still there. My apologies for the error. I have corrected the text above.
