### ISSUE TITLE
Private and public sepolicy seems to differ at 7.7 (API 30)

### ISSUE THREAD

**Issue by crazydrive22** [crdroidandroid/android#70]
This error happens at 7.7 only. 6.19 is working fine.
There seems to be a difference between the private and the public shell.te, what ends in an error.

[  2% 2406/80572] build out/target/product/matisselte/obj/FAKE/sepolicy_freeze_t
FAILED: out/target/product/matisselte/obj/FAKE/sepolicy_freeze_test_intermediates/sepolicy_freeze_test
/bin/bash -c "(diff -rq -x bug_map system/sepolicy/prebuilts/api/30.0/public system/sepolicy/public ) && (diff -rq -x bug_map system/sepolicy/prebuilts/api/30.0/private system/sepolicy/private ) && (touch out/target/product/matisselte/obj/FAKE/sepolicy_freeze_test_intermediates/sepolicy_freeze_test )"
Dateien system/sepolicy/prebuilts/api/30.0/public/shell.te und system/sepolicy/public/shell.te sind verschieden.
15:02:08 ninja failed with: exit status 1

**Comment by sileshn** [comment]
https://github.com/sileshn/android_system_sepolicy/commit/805ff2e4bc86d6746c50f62d0f5f0b70c66d57bc
