### ISSUE TITLE
Bluetooth audio not working (audio plays over phone speakers)

### ISSUE THREAD

**Issue by QuinTeknoLife** [crdroidandroid/android#71]
I've dropped this issue in the xda-dev thread as well but dev hasn't responded to my post there.

I am unable to play audio over BT. My audio devices connect properly and are visible in the new droid 11 audio manager, but when I actually select the BT audio device audio just keeps playing over the phone speaker (even though the audio tab clearly states JBL GO or whatever BT audio device I am using at the time). It also seems like the volume slider in the new audio tab is stuck on 0 even though it states it is active.

**Comment by gwolf2u** [comment]
issue is device specific
GitHub is for code specific issues, so for now your best bet is answer from maintainer
