### ISSUE TITLE
GMS/GAPPS

### ISSUE THREAD

**Issue by debdeep98** [crdroidandroid/android#72]
Hey. Sorry if this is a noob question but I can't seem to figure out a way to add gapps to the build and I have nowhere/no-one else to ask. I'm building for RMX206X (realme 6pro) and due to an issue with the device flashing gapps packages after ROM doesn't work so I need to include it in build.
I tried Opengapps method of including gapps but had clone issue. I suppose there aren't any flags to enable gapps either. Any help would be appreciated. Thanks.

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_device_oneplus_sm8350-common/commit/b7a1d6de9b3670c4382aa1fc25e2b2115077b158

https://gitlab.com/crdroidandroid/android_vendor_gapps

**Comment by gwolf2u** [comment]
clone our gapps and include mk file
```
<remote name="GL" fetch="https://gitlab.com/crdroidandroid" revision="11.0" />
<project path="vendor/gapps" name="android_vendor_gapps" remote="GL" />
```
https://github.com/crdroidandroid/android_device_oneplus_sm8350-common/blob/11.0/common.mk#L36

**Comment by debdeep98** [comment]
Thank you.

**Comment by grimanos** [comment]
Heyy is this working for Android 13 also?
