### ISSUE TITLE
Audio Issues while on Shuffle

### ISSUE THREAD

**Issue by NGC602** [crdroidandroid/android#78]
Good day. First and foremost I love this project, out of all the Custom ROMS available for the OP7+ this is **hands down** the best.

After updating to the most recent version of CRDroid (7.14) I have been unable to reliably skip songs in Media Players when the media is set to "SHUFFLE"

When _not_ on Shuffle, the audio plays fine from file - file, but when shuffled the audio service seems to crash entirely after playing through one song. I have attatched a LogCat, please let me know if any further information can be provided to help resolve this or if I can do anything on my end to troubleshoot. 

Thank you

----LOGCAT----

[alogcat.2022-01-25-12-56-00-0800.txt](https://github.com/crdroidandroid/android/files/7937114/alogcat.2022-01-25-12-56-00-0800.txt)

**Comment by gwolf2u** [comment]
please send support questions in respective device community forum or telegram
github is more for code review and code issues

**Comment by NGC602** [comment]
UPDATE:
Updating to CRDroid 7.15 fixed this issue

Thanks Dev team for all your hard work!
