### ISSUE TITLE
Intent filter verification service keeps stopping

### ISSUE THREAD

**Issue by J4gQBqqR** [crdroidandroid/android#79]
https://paste.crdroid.net/DGa2Dw

Model: One plus 7 pro
crDroid 8.1 01/30/2022 patch

![Screenshot_20220206-073226_MatLog](https://user-images.githubusercontent.com/77554817/152680914-59241a34-b1f0-46f8-bd47-ff66b0ef3dd8.png)

[download log file](https://nextcloud.quantimpulse.com/index.php/s/ZFHyCzr26Ct3Cb3)

**Comment by J4gQBqqR** [comment]
https://gitlab.com/CalyxOS/calyxos/-/issues/831

**Comment by J4gQBqqR** [comment]
This is really annoying, it pops up every 3 minutes, making the OS totally unusable.

**Comment by gwolf2u** [comment]
> https://gitlab.com/CalyxOS/calyxos/-/issues/831

That is not a fix, but rather a method to hide the error
For now recommend clean flash with nikgapps core and add mods back and all one by one if you use any

**Comment by J4gQBqqR** [comment]
I do not use GAPPS, nor do I plan to use it in the future. I guess I will have to wait for better solution in the future while switch to A11 for now.

Thank you for the explanation.

**Comment by gwolf2u** [comment]
please provide full logcat

**Comment by J4gQBqqR** [comment]
> please provide full logcat

I modified the log file link in the top post. Please find updated log file in the link.

**Comment by J4gQBqqR** [comment]
As soon as the phone connects to WIFI after reboot, this error will pop up. After that it randomly pops up every 3 minutes or so.

**Comment by neobuddy89** [comment]
Share proper log. 
I cannot reproduce such error on any device.

**Comment by J4gQBqqR** [comment]
I don't know how to reproduce the error for you nor do I know how to produce proper log. 
Sorry.
Closing the ticket.

**Comment by gwolf2u** [comment]
you should have just adb logcat and send file

**Comment by J4gQBqqR** [comment]
https://bw.quantimpulse.com/#/send/jOtsWg9vQh-rhdtr5CucOw/SZ6-Qslyr4qRLkG0PPChEQ

**Comment by J4gQBqqR** [comment]
This is a trace file from developer settings.
Not sure if this is deemed a proper log file.

**Comment by J4gQBqqR** [comment]
![Screenshot_20220206-104640_crDroid Home](https://user-images.githubusercontent.com/77554817/152688922-2c1937b1-09fe-47e3-b699-f569a221e692.png)
List of apps installed.
