### ISSUE TITLE
LiveDisplay QS Tile Disappears on Reboot

### ISSUE THREAD

**Issue by hokiealumnus** [crdroidandroid/android#8]
Confirmed on m8 and vs985. Steps to reproduce:

1) Add LiveDisplay tile to quick settings.
2) Confirm it functions as normal.
3) Reboot
4) LiveDisplay tile is gone from QS and you have to manually re-add it.

**Comment by neobuddy89** [comment]
Initialization of livedisplay service takes place after boot completes - this is why tile creation during boot errors out and disappears. CM way is to publish tile using their own API. Unfortunately they havent implemented their custom tile API yet. Will check more.

**Comment by hokiealumnus** [comment]
Ahh, makes sense. Thanks for the explanation. I'll just tell them it's a LOS problem right now, and we'll fix it if we can, otherwise wait on LOS. :)

**Comment by neobuddy89** [comment]
@hokiealumnus 

Added fix: https://github.com/crdroidandroid/cm_platform_sdk/commit/a3324fb44f4d3e5a2d6714abf9f68354aec4b0b8

Check if this fix helps.

**Comment by hokiealumnus** [comment]
The bug still exists on the latest source. I think you can mark this one as a LOS problem due to their API (or lack thereof).
