### ISSUE TITLE
Need forks for Cloudflare and AdGuard DNS

### ISSUE THREAD

**Issue by ShevT** [crdroidandroid/android#80]
https://android.googlesource.com/platform/frameworks/libs/net
https://github.com/LineageOS/android_packages_modules_Connectivity

**Comment by gwolf2u** [comment]
https://github.com/crdroidandroid/android_frameworks_libs_net
https://github.com/crdroidandroid/android_packages_modules_Connectivity

**Comment by ShevT** [comment]
PR - Done
