### ISSUE TITLE
Quick settings can be used if device is locked

### ISSUE THREAD

**Issue by TheJohnize** [crdroidandroid/android#81]
On my device (alioth) i can use nearly ALL quick settings tiles like mobile data and even NFC. So if the device gets lost, everyone can disable the internet or use NFC.
Would be very appreciated to look for a fix.

CRDroid Version 8.1 Android 12

**Comment by gwolf2u** [comment]
we are working to bring ability to disable QS tiles on secure lockscreen 
will be up with upcoming updates
