### ISSUE TITLE
"Double press power button to open camera" does not prompt for camera app selection when triggered from locked phone on crDroid 8.2

### ISSUE THREAD

**Issue by JanPokorny** [crdroidandroid/android#84]
How to reproduce:
1. Install multiple camera apps (eg. default camera and Open Camera)
2. Set a screen lock
3. Enable "double tap power button to open camera"
4. Lock phone
5. Double tap power button

What should happen:
- phone prompts for screen lock, then after unlocking shows the "open with" prompt to choose a camera application

What does happen:
- phone prompts for screen lock, then after unlocking no prompt appears

What have I tried:
- trying from unlocked phone: prompt appears and allows to select camera app, but has no effect on locked phone
- removing screen lock, setting app and re-enabling it -- no luck

Workaround:
- have only one camera app installed (impractical when you actually use more, like Google Camera for HDR and default camera for selfies)

**Comment by JanPokorny** [comment]
After many tries it just worked one time, the menu popped up and now the shortcut works. I tried it many times before writing this issue, but that's Murphy's law I guess. This should be pretty easy to replicate if universal, so you'll see.

**Comment by gwolf2u** [comment]
working fine here
3 devices

**Comment by JanPokorny** [comment]
@gwolf2u I was able to confirm with user of the same device (daisy, aka Mi A2 Lite) that they experience this too, and they also revealed that what helps is waiting some time after double-pressing the power button before unlocking the phone. Since daisy is a rather slow device, this may explain how the bug is triggered. Just leaving this here in case someone stumbles upon this from search, it's probably not worth fixing since the workaround is simple and the affected range of devices rather small.
