### ISSUE TITLE
Default camera app is saving photos in a non-standard location

### ISSUE THREAD

**Issue by JanPokorny** [crdroidandroid/android#85]
The default camera app on crDroid 8.2 is saving photos to the folder `Pictures`. However, the standard location for photos is some subfolder of `DCIM`. By convention, `Pictures` is used to save downloaded images (from Messenger, Telegram, Reddit etc.) and saving directly to this folder makes it impossible to back up photos to Google Photos while excluding the downloaded pictures.

For comparison: Google Camera saves to `DCIM/Camera`, OpenCamera saves to `DCIM/OpenCamera`.

Proposal: save pictures to `DCIM/Camera`, or perhaps `DCIM/crDroidCamera`.

**Comment by gwolf2u** [comment]
Can't confirm
What crDroid version you use?

**Comment by JanPokorny** [comment]
@gwolf2u crDroid 8.2, device daisy (Xiaomi Mi A2 Lite)

Screenshot from inside the camera app, showing photo location at the bottom:

![Screenshot_20220306-190327_Camera](https://user-images.githubusercontent.com/4580066/156935898-f5848a77-a294-4b35-8975-95cd3154f043.png)

**Comment by gwolf2u** [comment]
might be camera app related
do you know if it's Camera2?
else, what build date is your crDroid?
we just changed default camera app

**Comment by JanPokorny** [comment]
@gwolf2u Build date is 2022-02-14 (latest for daisy). Camera app is com.android.camera2 version 2.0.002

**Comment by gwolf2u** [comment]
Then issue should be fixed in upcoming updates

**Comment by JanPokorny** [comment]
@gwolf2u Thanks, in that case I'm closing. BTW, what is the new default camera app?

**Comment by gwolf2u** [comment]
CameraGo, but not yet decided if we stay with it

**Comment by JanPokorny** [comment]
@gwolf2u That seems like a good choice to me.
