### ISSUE TITLE
Cepheus | Random freeze, often when charging

### ISSUE THREAD

**Issue by ElSebita** [crdroidandroid/android#86]
I installed crDroid 8 from clean. It works nicely but it has this freeze problem that leaves the phone unusable, the only way out is forcing reboot using power button. In that state, sometimes the screen turns on but it's not responsive. It misses alarms.
It happened with crDroid 7 too and it was the motive to jump to crDroid 8, but problem persists. It often happens when charging but not always. With crDroid 7 one day I had 5 hangs in a 2 hour window.
Log attached.
[logs-2022-03-13-18-43-59.zip](https://github.com/crdroidandroid/android/files/8275796/logs-2022-03-13-18-43-59.zip)

**Comment by gwolf2u** [comment]
please include logcat to device maintainer in the forum or if available telegram chat
GitHub is for source specific related issues not device specific
