### ISSUE TITLE
Errors on sweet (Redmi Note 10 Pro)

### ISSUE THREAD

**Issue by Schweber** [crdroidandroid/android#88]
On Sweet i frequently have to click on something twice because the first time it only kind of long clicks/"right clicks" (the button is marked/highlighted and sometimes additional information is displayed that is never in normal usage or in some apps like launchers it registers a long click). This did not happen with ArrowOS Android 11 on the same device and also does not happen on my other device with crdroid (mojito / Redmi Note 10 / latest crdroid).

Also, when doing the swipe up gesture from the bottom to enter the home screen it frequently shortly shows an app drawer or something like that but not always. This problem also occurd on ArrowOS and does not occour on my mojito deveice with crdroid.

In the error log i constantly see an error related to an ultrasound sensor. Maybe this is related to the bottom swipe up problem.

It would be kind of you, if you could fix these issues. Thank you for your work and your nice ROM!

Also as a feature request: in ArrowOS i could chosse how the device shoudl react to detecting a fingerprint on the Power Button (unlock immediately or wait for button press and then unlock). In crdroid i cannot select this behaviour which is inconvenient on the Redmi Note 10 Pro because its easy to unlock it by accident when just handling the phone.

[logs-2022-03-23-11-58-12.zip](https://github.com/crdroidandroid/android/files/8332435/logs-2022-03-23-11-58-12.zip)

**Comment by gwolf2u** [comment]
please provide this logcat to device maintainer
as your issue can't be reproduced on all devices aka device specific, you need to get help from the forum or telegram if available

**Comment by Schweber** [comment]
Sorry

**Comment by Schweber** [comment]
> please provide this logcat to device maintainer as your issue can't be reproduced on all devices aka device specific, you need to get help from the forum or telegram if available

I posted the issue twice in the "android_device_xiaomi_sweet" category and it got deleted both times without comment.

I find this highly unusual, can you please explain it to me? How am i to post the issue correctly?
