### ISSUE TITLE
Bootloop due to huge memory leak in bootanimation process

### ISSUE THREAD

**Issue by iusmac** [crdroidandroid/android#89]
Hi!

After upgrading form 12.0 to 12.1 my device became unbootable. I've examined all logs and discovered an 'out of memory' problem during the boot phase.
```ruby
[   82.797137] Out of memory: Kill process 1837 (system_server) score 0 or sacrifice child
[   82.797844] Killed process 1837 (system_server) total-vm:7874432kB, anon-rss:73360kB, file-rss:192468kB, shmem-rss:584kB
```

According to `htop` command, the most expensive process is `/system/bin/bootanimation` binary file. Also, after a certain point the bootanimation freezes or stops completely.
![htop-memleak-bootanim](https://user-images.githubusercontent.com/28353279/160292889-a96f946f-2a82-4f92-b2d0-e75f0624c535.png)

The phone is able to boot properly if I disable the bootanimation using the following prop in `/vendor/build.prop`:
```
debug.sf.nobootanimation=1
```
Devices with 3GB or more of RAM will most likely not suffer from this, as bootanimation is a short-lived process so the memory is freed up quickly and doesn't cause processes to be killed.

P.S I don't know if this is a crDroid or LOS bug, so I leave this issue here ;)

**Comment by neobuddy89** [comment]
This should be fixed with below workaround in latest source
https://github.com/crdroidandroid/android_frameworks_base/commit/386d7b87807d02df6c0f327821b6333b3d03e1d4
