### ISSUE TITLE
SD Card corrupted when used as internal space

### ISSUE THREAD

**Issue by crazydrive22** [crdroidandroid/android#93]
Hi.

I'm building crDroid 6 and 7 unofficial for Samsung Galaxy Tab 4 (Matisse and Millet)

A User of sm-t530 and crDroid 7.x is facing the following issue. Maybe you can help in this case? 
DMESG is attached. I'm not sure but the issue could start at line 772.

Cheers 
Martin

"I've tested it and the bug is even more strange than I thougt. Here's the full description:

1.
If you install a SD-Card and format it as internal space (f2fs) with crDroid, everything seems do be fine. Even if you restart the device several times, the SD-Card is being mounted as it should be without any problems.

But as soon as you install an app (that's being stored on the SD-Card automatically), the SD-Card is being recognized as "corrupt" after every restart of the device. If you eject and reinstall the SD-Card, it gets recognized correctly.

2.
There is a second problem with the f2fs SD-Card. The widgets of all apps, which are installed on the SD-Card, do not exist. You can test this with "VLC for Android" or "Amazon Music" (I did so). If you install them without using an f2fs SD-Card, these apps provide widgets. If you are using a f2fs SD-Card, there are no widgets (Even immediately after the installation without a restart).

I've tested this all on a 6.27 image with 3 different SD-Cards. 2 GB Samsung, 4 GB Samsung, 128 GB SanDisk Extreme. It was always the same. Using them as external space (vfat & extfat) caused no problems."

Edit:
Now with dmesg

https://www.toptal.com/developers/hastebin/ekuzapoyog.yaml

**Comment by gwolf2u** [comment]
try upstreaming kernel if you use f2fs
do also test with ext4 to see maybe issue resides somewhere else
