### ISSUE TITLE
"Mic and camera privacy indicator" setting does nothing, "Location privacy indicator" controls both

### ISSUE THREAD

**Issue by SeerLite** [crdroidandroid/android#95]
In crDroid Settings -> Status Bar

At least that's the behavior I observed for microphone. Didn't test camera.

crDroid 8.6, Android 12.1

**Comment by neobuddy89** [comment]
Should be fixed here: https://github.com/crdroidandroid/android_frameworks_base/commit/6ed5e14a4159c95961ec13e60e57a6c42681fb00

**Comment by SeerLite** [comment]
Thank you!
