### ISSUE TITLE
Problems compiling for Xiaomi Redmi Note 11 (spes)

### ISSUE THREAD

**Issue by outtaspes** [crdroidandroid/android#96]
Hello,

I looked for a way to compile crDroid for spes. The goal is to do it without Google apps. First I just wanted a clean run. My approach was:

0. create custom roomservice.xml
1. follow README.md on this repo

Content of `.repo/local_manifests/custom_roomservice.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project path="kernel/xiaomi/spes" remote="github" name="jabiyeff/kernel_xiaomi_spes_header" revision="12" />
  <project path="device/xiaomi/spes" remote="github" name="crdroidandroid/android_device_xiaomi_spes" revision="12.1" />
  <project path="vendor/xiaomi/spes" remote="github" name="crdroidandroid/android_vendor_xiaomi_spes" revision="12.1" />
</manifest>
```
Also tried with @Jabiyeff 's repos for everything.

At first the result is:
> build/make/core/base_rules.mk:335: error: hardware/google/pixel/kernel_headers: MODULE.TARGET.HEADER_LIBRARIES.qti_kernel_headers.recovery already defined by kernel/xiaomi/spes.

Removing that part in `hardware/google/pixel/kernel_headers/Android.bp` gets you pretty far, but it ends with something like:
> The following HALs in device manifest are not declared in FCM <= level 5: 
android.hardware.power@1.3::IPower/default
files are incompatible: Device manifest and framework compatibility matrix are incompatible: HALs incompatible. Matrix level = 5. Manifest level = 5. The following requirements are not met: android.hardware.power:
required: IPower/default (@1-2)
provided: @1.3::IPower/default

This is already the result of a try I must admit. Previously it said "provided: ". 

I only modified these two files as explained and in that order: 
```
hardware/google/pixel/kernel_headers/Android.bp
device/xiaomi/spes/configs/hidl/manifest.xml
```

Could someone tell me what I am doing wrong here?

**Comment by Jabiyeff** [comment]
These are not source issue, so no need create "issue" on this repo. Also, spes has official crDroid support already.

**Comment by outtaspes** [comment]
> These are not source issue, so no need create "issue" on this repo. Also, spes has official crDroid support already.

I admittedly didn't notice when it was moved to official repository. So, is my assumption correct that I can remove the roomservice.xml and it should build, otherwise it is a source issue?

**Comment by gwolf2u** [comment]
because we don't use dependencies file
