### ISSUE TITLE
README.md outdated

### ISSUE THREAD

**Issue by outtaspes** [crdroidandroid/android#98]
Hello,

Following the steps in this repository pulls LineageOS device/kernel/vendor sources and in many cases does not work at all (because they are missing in LineageOS).

**Comment by gwolf2u** [comment]
your device specific stuff, you'll need to add to roomservice.xml in the .repo/local_manifests

**Comment by outtaspes** [comment]
That is not mentioned in the README.md and it doesn't work either. At least for supported devices the README.md should work, otherwise it is misleading.

**Comment by gwolf2u** [comment]
nothing is misleading 
as I said, we don't use dependencies so official or not, will not sync from our github org
you need to edit your manifest with your device source

**Comment by outtaspes** [comment]
> as I said, we don't use dependencies so official or not, will not sync from our github org

What dependencies do you not use?

> nothing is misleading

The README.md workflow does not work at all. It is therefore misleading to keep it like it is.

Ultimately, is it intended that the compilation process is a mystery for outsiders?

> you need to edit your manifest with your device source

As described in #96 I did exactly this, but it doesn't work. Tho it is not clear if kernel/device/vendor for the device are enough. I didn't get a useable answer and of course it's not part of the README.md.

**Comment by DrFunkenbreakz** [comment]
I am a  "outsider". I can build for 4 of my devices using the readme. Just takes some common sense and research. Nothing needs to be changed.

Realistically, the readme can't be simplified any more than it already is.

**Comment by gwolf2u** [comment]
> What dependencies do you not use?

crdroid.dependencies file 
LOS uses lineage.dependencies ex: https://github.com/LineageOS/android_device_oneplus_guacamole/blob/lineage-19.1/lineage.dependencies

> The README.md workflow does not work at all. It is therefore misleading to keep it like it is.
> Ultimately, is it intended that the compilation process is a mystery for outsiders?

the README is just to get crDroid source and not for device specific repos

> As described in #96 I did exactly this, but it doesn't work. Tho it is not clear if kernel/device/vendor for the device are enough. I didn't get a useable answer and of course it's not part of the README.md.

device, device-common (if available), vendor and kernel are needed to be in your manifest
if you use dt that is not compatible, will also not work
you'll need to make sure there's a lineage_device.mk file with said device info in it

**Comment by outtaspes** [comment]
> the README is just to get crDroid source and not for device specific repos

```
# Run to prepare our devices list
$ . build/envsetup.sh
# ... now run
$ brunch "your device codename"
```
Is there in the README.md which does not work according to your own explanation.

> device, device-common (if available), vendor and kernel are needed to be in your manifest
if you use dt that is not compatible, will also not work

I guess you mean device tree with "dt". Did you read the initial issue in #96 ? I did that and it doesn't work. It's also mentioned nowhere in the README.md. 

At this point it's more honest to just remove any build instructions and/or say "use common sense" as @DrFunkenbreakz proposed.

@DrFunkenbreakz Nowhere did I call for simplification of the README.md. I called for correctness. Your vague statement about common sense does not help and does not change the fact that the README.md is misleading.
