### ISSUE TITLE
Upgrade crashes when trying to update to 24.07.2022 build on Oneplus 9 Pro

### ISSUE THREAD

**Issue by michaelelleby** [crdroidandroid/android#99]
Trying to upgrade from 14.07.2022 to 24.07.2022 build on Oneplus 9 Pro crashes, see log here https://paste.crdroid.net/rO6aAU

Tried both OTA upgrade and local upgrade, both crashing.

**Comment by gwolf2u** [comment]
Do check with forum
All info there
